set(ZERO_AUTHORS "Gabriele Dragotto, Sriram Sankaranarayanan")
set(ZERO_VERSION_MAJOR 1)
set(ZERO_VERSION_MINOR 0)
set(ZERO_VERSION_PATCH 1)
set(ZERO_V "${ZERO_VERSION_MAJOR}.${ZERO_VERSION_MINOR}.${ZERO_VERSION_PATCH}")
set(ZERO_DESC "ZERO is a multi-purpose game solver")

# CXX Options
set(CXX ON)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 17)
